[package]
name = "web30"
version = "0.10.5"
authors = ["Michal Papierski", "Jehan Tremback", "Justin Kilpatrick"]
description = "Async endian safe web3 library"
license = "Apache-2.0"
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clarity = "0.4"
num256 = "0.3"
futures = "0.3"
actix-web = {version = "3",  default-features = false, features=["openssl", "compress"]}
tokio = {version = "0.2", features=["macros", "time"]}
actix = "0.10"
log = "0.4"
num = "0.3"

[dev-dependencies]
assert-json-diff = "2"
env_logger = "0.8"

